version: '3.1'

services:
  hermes-mysql:
    container_name: hermes-mysql
    build:
      context: ./mysql
      dockerfile: dev.Dockerfile
    env_file:
      - api/env/mysql/.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  hermes-api:
    container_name: hermes-api
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    command: npm run start
    env_file:
      - api/env/node/.env
    depends_on:
      - hermes-mysql
