version: '3.9'

services:
  hermes-db:
    container_name: hermes-db
    image: postgres
    restart: always
    volumes:
      - hdb:/var/lib/postgresql/data
    env_file:
      - ./.env
  hermes-api:
    container_name: hermes-api
    build:
      context: api
      dockerfile: Dockerfile
      target: ${TARGET}
    ports:
      - ${EXTERN_PORT}:${DEFAULT_PORT}
    env_file:
      - ./.env
    depends_on:
      - hermes-db

volumes:
  hdb: